# Generated by Django 4.0.4 on 2022-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology', models.CharField(max_length=1024)),
                ('decisional_model', models.CharField(max_length=64)),
                ('num_controllers', models.FloatField(default=1.0)),
                ('data_frequency', models.IntegerField(default=1)),
            ],
        ),
    ]
